### ISSUE TITLE
Unable to use substitution macros in classes config section

### ISSUE THREAD

**Issue by adrienlauer** [seedstack/seed#283]
It seems that values of the `classes` config section are not evaluated properly or something is blocking that ability. So a section like this will always have it's `mongoDbDatabase` value empty:

```
classes:
  com:
    inetpsa:
      msj:
        core:
          domain:
            model:
              invoicingevent:
                defaultRepository: org.seedstack.mongodb.morphia.Morphia
                mongoDbClient: mefistoMongoClient
                mongoDbDatabase: ${env.MONGO_DATABASE:'MSJ_DB'}
              sourceevent:
                defaultRepository: org.seedstack.mongodb.morphia.Morphia
                mongoDbClient: mefistoMongoClient
                mongoDbDatabase: ${env.MONGO_DATABASE:'MSJ_DB'}
              cancelevent:
                defaultRepository: org.seedstack.mongodb.morphia.Morphia
                mongoDbClient: mefistoMongoClient
                mongoDbDatabase: ${env.MONGO_DATABASE:'MSJ_DB'}
```
